# Astropy documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this file.
#
# All configuration values have a default. Some values are defined in
# the global Astropy configuration which is loaded here before anything else.
# See astropy.sphinx.conf for which values are set there.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))
# IMPORTANT: the above commented section was generated by sphinx-quickstart, but
# is *NOT* appropriate for astropy or Astropy affiliated packages. It is left
# commented out with this explanation to make it clear why this should not be
# done. If the sys.path entry above is added, when the astropy.sphinx.conf
# import occurs, it will import the *source* version of astropy instead of the
# version installed (if invoked as "make html" or directly with sphinx), or the
# version in the build directory (if "python setup.py build_sphinx" is used).
# Thus, any C-extensions that are needed to build the documentation will *not*
# be accessible, and the documentation will not build correctly.

import datetime
import os
import sys
import tomllib
from pathlib import Path

# Ensure documentation examples are deterministically random.
import numpy
import yaml
from importlib_metadata import distribution

try:
    numpy.random.seed(int(os.environ["SOURCE_DATE_EPOCH"]))  # noqa: NPY002
except KeyError:
    pass

try:
    from sphinx_astropy.conf.v1 import *  # noqa: F403
except ImportError:
    print("ERROR: the documentation requires the sphinx-astropy package to be installed")
    sys.exit(1)

# Get configuration information from pyproject.toml
with open(Path(__file__).parent.parent / "pyproject.toml", "rb") as configuration_file:
    conf = tomllib.load(configuration_file)
configuration = conf["project"]


# -- General configuration ----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.2'

intersphinx_mapping["pypa-packaging"] = ("https://packaging.python.org/en/latest/", None)  # noqa: F405
intersphinx_mapping["asdf"] = ("https://asdf.readthedocs.io/en/latest/", None)  # noqa: F405
intersphinx_mapping["asdf-standard"] = ("https://asdf-standard.readthedocs.io/en/latest/", None)  # noqa: F405
intersphinx_mapping["asdf-astropy"] = ("https://asdf-astropy.readthedocs.io/en/latest/", None)  # noqa: F405
intersphinx_mapping["pytest"] = ("https://docs.pytest.org/en/latest/", None)  # noqa: F405
intersphinx_mapping["roman_datamodels"] = ("https://roman-datamodels.readthedocs.io/en/latest/", None)  # noqa: F405

# To perform a Sphinx version check that needs to be more specific than
# major.minor, call `check_sphinx_version("x.y.z")` here.
# check_sphinx_version("1.2.1")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns.append("_templates")  # noqa: F405

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog += """"""  # noqa: F405

# -- Project information ------------------------------------------------------

# This does not *have* to match the package name, but typically does
project = configuration["name"]
author = configuration["authors"][0]["name"]
copyright = f"{datetime.datetime.now().year}, {configuration['authors'][0]['name']}"

release = distribution(configuration["name"]).version
# for example take major/minor
version = ".".join(release.split(".")[:2])

# -- Options for HTML output ---------------------------------------------------

# A NOTE ON HTML THEMES
# The global astropy configuration uses a custom theme, 'bootstrap-astropy',
# which is installed along with astropy. A different theme can be used or
# the options for this theme can be modified by overriding some of the
# variables set in the global configuration. The variables set in the
# global configuration are listed below, commented out.

# Add any paths that contain custom themes here, relative to this directory.
# To use a different custom theme, add the directory containing the theme.
# html_theme_path = []

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. To override the custom theme, set this to the
# name of a builtin theme or the name of a custom theme in html_theme_path.
html_theme = "sphinx_rtd_theme"

html_static_path = ["_static"]

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/stsci_logo.png"
html_logo = "_static/stsci_logo.png"

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = ''

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = f"{project} v{release}"

# Output file base name for HTML help builder.
htmlhelp_basename = project + "doc"


# -- Options for LaTeX output --------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [("index", project + ".tex", project + " Documentation", author, "manual")]

latex_logo = "_static/stsci_logo.png"


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", project.lower(), project + " Documentation", [author], 1)]

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname("__file__")), "sphinxext"))
extensions += ["sphinx_asdf"]  # noqa: F405


LATEST = Path("../latest")
LEGACY = Path("../src/rad/resources")
SCHEMAS = Path("./_schemas")

SCHEMAS.mkdir(exist_ok=True)


def pull_schemas(schema_path: Path) -> dict[tuple[str, str], str]:
    schemas = {}
    # Search files
    for file_path in schema_path.glob("**/*.yaml"):
        path = file_path.relative_to(schema_path)

        # Currently we do not document the SSC schemas
        if "SSC" in str(path):
            continue

        # No need to document the rad_schema
        if "rad_schema" in str(path):
            continue

        # No need to document automatically fps
        if "fps" in str(path):
            continue

        # No need to document automatically tvac
        if "tvac" in str(path):
            continue

        # This is used to find the version number of the schema
        #    We need to do this because of the way sphinx-asdf
        #    generates links between schemas, this requires us
        #    to have the version number included in the page
        #    url, which is easiest to accomplish by pointing
        #    spinx-asdf at src/rad/references instead of latest
        schema_dict = yaml.safe_load(file_path.read_bytes())

        entry = str(path.stem)
        if "-" not in entry:
            version = schema_dict["id"].split("-")[-1]
            entry = f"{entry}-{version}"

        # The archive_meta keyword distinguishes the level of the
        #    schemas going into the archive which makes it an easy
        #    way to separate all the different data model types
        filename = None
        if "archive_meta" in schema_dict:
            meta = "_".join(schema_dict["archive_meta"].split(" ")[:4])
            filename = f"{meta}.rst"

        # Now we generate the prefix for the asdf-autoschemas argument
        prefix = str(path.parent)
        if prefix == ".":
            prefix = "schemas"

        # If we don't have a filename lets build it from the prefix
        if filename is None:
            # empty prefix means top-level data model that is not
            #     archived. We dump these in the remaining file
            if prefix == "schemas":
                filename = "datamodels.rst"
            else:
                # Otherwise turn the prefix into something nice for a file name
                filename = f"{prefix.replace('/', '_')}.rst"

        # Now if we aren't a manifest in `src/rad/resources` we need
        #    to point in the schemas directory
        if prefix != "manifests" and not prefix.startswith("schemas"):
            prefix = f"schemas/{prefix}"

        # Create a key that will store this schema
        key = (prefix, filename)

        # Add a empty list if the key is not found
        if key not in schemas:
            schemas[key] = []

        # Add the key to the list in the schemas
        schemas[key].append(entry)

    return schemas


def write_schemas(schemas: dict[tuple[str, str], str], path: Path):
    for (prefix, filename), schema_list in schemas.items():
        # First line is the directive followed by the prefix
        #    argument on the next line followed by an empty
        #    line to create the sphinx directive.
        lines = [".. asdf-autoschemas::"]
        lines.append(f"   :standard_prefix: {prefix}")
        lines.append("")

        # Make the list alphabetical
        schema_list.sort()
        for schema in schema_list:
            # Standard indent of RST is supposed to be three spaces
            lines.append(f"   {schema}")

        # Add blank line at the end to close the directive properly
        lines.append("")

        # Write the doc file.
        with (path / filename).open(mode="w") as file:
            file.write("\n".join(lines))


latest_schemas = pull_schemas(LATEST)
all_schemas = pull_schemas(LEGACY)

latest_paths = []
for (prefix, _), value in latest_schemas.items():
    for suffix in value:
        latest_paths.append(f"{prefix}/{suffix}")

_manifest_key = ("manifests", "legacy_manifests.rst")
_schema_key = ("schemas", "legacy_schemas.rst")
legacy_schemas = {
    _manifest_key: [],
    _schema_key: [],
}
for (prefix, _), value in all_schemas.items():
    for suffix in value:
        if (schema := f"{prefix}/{suffix}") not in latest_paths:
            if schema.startswith(_manifest_key[0]):
                legacy_schemas[_manifest_key].append(suffix)
            else:
                legacy_schemas[_schema_key].append(schema.removeprefix("schemas/"))

write_schemas({**latest_schemas, **legacy_schemas}, SCHEMAS)


def setup(app):
    app.add_css_file("custom.css")


# -- sphinx_asdf configuration ---------------------------------------------

# Top-level directory containing ASDF schemas (relative to current directory)
# NOTE: This has to be this and not latest because of how sphinx-asdf will generate
# links between schemas.
asdf_schema_path = "../src/rad/resources"
# This is the prefix common to all schema IDs in this repository
asdf_schema_standard_prefix = "schemas"
asdf_schema_reference_mappings = [
    (
        "asdf://stsci.edu/datamodels/roman/tags/calibration_software_name-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/calibration_software_name-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/calibration_software_version-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/calibration_software_version-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/filename-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/filename-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/file_date-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/file_date-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/model_type-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/model_type-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/origin-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/origin-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/prd_version-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/prd_version-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/product_type-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/product_type-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/sdf_software_version-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/sdf_software_version-1.0.0.html",
    ),
    (
        "asdf://stsci.edu/datamodels/roman/tags/telescope-1.0.0",
        "https://rad.readthedocs.io/en/latest/generated/schemas/tagged_scalars/telescope-1.0.0.html",
    ),
    ("asdf://stsci.edu/datamodels/roman/tags/", "https://rad.readthedocs.io/en/latest/generated/schemas/"),
    ("asdf://stsci.edu/datamodels/roman/schemas/", "https://rad.readthedocs.io/en/latest/generated/schemas/"),
    ("http://stsci.edu/schemas/asdf/", "https://asdf-standard.readthedocs.io/en/latest/generated/stsci.edu/asdf/"),
    ("tag:stsci.edu:gwcs/wcs-*", "https://asdf-wcs-schemas.readthedocs.io/en/latest/generated/gwcs/wcs-1.0.0.html"),
]

# Enable nitpicky mode - which ensures that all references in the docs resolve.
nitpicky = True
nitpick_ignore = []
