from typing import Any

from ._tagged import TaggedObjectNode

class AbvegaoffsetRef(TaggedObjectNode): ...
class ApcorrRef(TaggedObjectNode): ...
class DarkdecaysignalRef(TaggedObjectNode): ...
class DarkRef(TaggedObjectNode): ...
class DetectorstatusRef(TaggedObjectNode): ...
class DistortionRef(TaggedObjectNode): ...
class EpsfRef(TaggedObjectNode): ...
class FlatRef(TaggedObjectNode): ...
class ForcedImageSourceCatalog(TaggedObjectNode): ...
class ForcedMosaicSourceCatalog(TaggedObjectNode): ...
class Fps(TaggedObjectNode): ...
class GainRef(TaggedObjectNode): ...
class Guidewindow(TaggedObjectNode): ...
class ImageSourceCatalog(TaggedObjectNode): ...
class IntegralnonlinearityRef(TaggedObjectNode): ...
class InverselinearityRef(TaggedObjectNode): ...
class IpcRef(TaggedObjectNode): ...
class L1DetectorGuidewindow(TaggedObjectNode): ...
class L1FaceGuidewindow(TaggedObjectNode): ...
class LinearityRef(TaggedObjectNode): ...
class MaskRef(TaggedObjectNode): ...
class MatableRef(TaggedObjectNode): ...
class MosaicSegmentationMap(TaggedObjectNode): ...
class MosaicSourceCatalog(TaggedObjectNode): ...
class MsosStack(TaggedObjectNode): ...
class MultibandSegmentationMap(TaggedObjectNode): ...
class MultibandSourceCatalog(TaggedObjectNode): ...
class PixelareaRef(TaggedObjectNode): ...
class Ramp(TaggedObjectNode): ...
class RampFitOutput(TaggedObjectNode): ...
class ReadnoiseRef(TaggedObjectNode): ...
class RefpixRef(TaggedObjectNode): ...
class SaturationRef(TaggedObjectNode): ...
class SegmentationMap(TaggedObjectNode): ...
class SkycellsRef(TaggedObjectNode): ...
class SuperbiasRef(TaggedObjectNode): ...
class Tvac(TaggedObjectNode): ...
class WfiImage(TaggedObjectNode): ...
class WfiImgPhotomRef(TaggedObjectNode): ...
class WfiMosaic(TaggedObjectNode): ...
class WfiScienceRaw(TaggedObjectNode): ...
class WfiWcs(TaggedObjectNode): ...

_MANIFESTS: list[dict[str, Any]]
