name: Generate Archive Information

on:
  push:
    branches:
      - main
      - "*"
    tags:
      - "*"
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  generate-archive-info:
    name: Generate archive information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/spacetelescope/roman_datamodels.git

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Install RAD
        run: |
          pip install -e "packages/rad[test]"

      - name: Generate archive information
        run: |
          python packages/rad/scripts/archive.py --save_dir="${{ github.workspace }}/archive"

      - name: Upload archive information
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: archive
          path: ${{ github.workspace }}/archive/
