name: changelog

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-entry-needed') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: 3
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - run: pip install .
      - run: pip install towncrier
      - run: towncrier check
      - run: towncrier build --draft | grep -P '#${{ github.event.number }}'
